create table orders_o_orderkey (c1 integer, w1 integer, tid integer, o_orderkey integer);
create table orders_o_custkey (c1 integer, w1 integer, tid integer, o_custkey integer);
create table orders_o_orderstatus (c1 integer, w1 integer, tid integer, o_orderstatus varchar);
create table orders_o_totalprice (c1 integer, w1 integer, tid integer, o_totalprice float);
create table orders_o_orderdate (c1 integer, w1 integer, tid integer, o_orderdate varchar);
create table orders_o_orderpriority (c1 integer, w1 integer, tid integer, o_orderpriority varchar);
create table orders_o_clerk (c1 integer, w1 integer, tid integer, o_clerk varchar);
create table orders_o_shippriority (c1 integer, w1 integer, tid integer, o_shippriority varchar);
create table orders_o_comment (c1 integer, w1 integer, tid integer, o_comment varchar);